title: Long Haul
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://yonseisreda.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 3

navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  - title: Contact
    url: /contact

social:
  github: yonseisreda
  email: catherine666@gmail.com

google_analytics: "UA-137806717-1"
